Added ExpressionLanguage to the plugin, added example config files, u…
php-etl/spreadsheet-plugin pull request #3
Opened 2021-05-25 15:19 UTC by sebprt

- Ajout d'ExpressionLanguage dans le plugin 
- Ajout de fichiers d'example de config
- Mise à jour des tests

2021-05-27 08:38 UTC, gplanchat requested changes

2021-05-27 08:38 UTC, gplanchat commented on src/Configuration/Extractor.php
> +                            ->defaultValue(0)
Est-ce que tu peux également permettre d'utiliser ExpressionLanguage sur cette option ?

2021-05-27 08:38 UTC, gplanchat commented on src/Factory/Extractor.php
> +    }
Tu as la fonction `compileValueWhenExpression()` dans `php-etl/satellite-toolbox` qui te permet de faire ça.

2021-05-28 07:22 UTC, sebprt commented on src/Configuration/Extractor.php
> +                            ->defaultValue(0)
Fait

2021-05-28 09:06 UTC, gplanchat requested changes

2021-05-28 09:06 UTC, gplanchat commented on src/Factory/Extractor.php
> +                compileValue($this->interpreter, $config['excel']['skip_lines'])
Ici, le `compileValue` ne fonctionnera que si tu disposes d'une expression, pas si on place directement un `int`

2021-05-31 10:16 UTC, sebprt commented on src/Factory/Extractor.php
> +                compileValue($this->interpreter, $config['excel']['skip_lines'])
J'ai corrigé, ça devrait être bon

2021-05-31 12:34 UTC, gplanchat commented
La CI ne trouve plus phpunit, il a été retiré ?

2021-05-31 12:35 UTC, gplanchat requested changes

2021-05-31 12:35 UTC, gplanchat commented on src/Configuration/Extractor.php
> +                                ->thenInvalid('The skip_lines option should be an integer or an Expression value.')
Remplaces le message par :

> The skip_lines option should result in an integer value.

2021-05-31 15:13 UTC, sebprt commented
> La CI ne trouve plus phpunit, il a été retiré ?

Non

2021-05-31 15:16 UTC, sebprt commented on src/Configuration/Extractor.php
> +                                ->thenInvalid('The skip_lines option should be an integer or an Expression value.')
Fait

2021-06-07 08:24 UTC, gplanchat requested changes

2021-06-07 08:24 UTC, gplanchat commented on src/Factory/Extractor.php
> +                $config['excel']['skip_lines'] instanceof Expression ? compileValueWhenExpression($this->interpreter, $config['excel']['skip_lines']) : compileValue($this->interpreter, $config['excel
Ici, le `compileValueWhenExpression()`, dans le cas où nous n'avons pas d'expression va te renvoyer un `Node\Scalar\String`, mais ton code généré va demander plutôt un `Node\Scalar\LNumber`.

2021-06-07 08:24 UTC, gplanchat commented on src/Factory/Extractor.php
> +                $config['open_document']['skip_lines'] instanceof Expression ? compileValueWhenExpression($this->interpreter, $config['open_document']['skip_lines']) : compileValue($this->interpreter
Idem, le `compileValueWhenExpression()`, dans le cas où nous n'avons pas d'expression va te renvoyer un `Node\Scalar\String`, mais ton code généré va demander plutôt un `Node\Scalar\LNumber`.

2021-06-07 08:24 UTC, gplanchat commented on src/Factory/Extractor.php
> +                $config['csv']['skip_lines'] instanceof Expression ? compileValueWhenExpression($this->interpreter, $config['csv']['skip_lines']) : compileValue($this->interpreter, $config['csv']['sk
Idem, le `compileValueWhenExpression()`, dans le cas où nous n'avons pas d'expression va te renvoyer un `Node\Scalar\String`, mais ton code généré va demander plutôt un `Node\Scalar\LNumber`.

2021-06-07 08:58 UTC, gplanchat approved these changes

2021-06-07 09:01 UTC, merged